[package]
name = "search-wikipedia"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.*"
reqwest = { version = "*", features = ["blocking", "json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
colored = "*"
colored_json = "*"
